# Site settings
title: 'rhythmcity.github.io' # Your Title
tagline: '既然选择了一条路，又何必打听要走多久。' # A brief tagline for your site
sidebar_image: /images/cover.jpg

# Build settings
markdown: redcarpet
highlighter: pygments
baseurl:/rhythmcity
# the subpath of your site, e.g. /blog/
