# Site settings
title: 'rhythmcity.github.io' # Your Title
tagline: 'yyyyyyyy。' # A brief tagline for your site
sidebar_image: /images/cover.jpg

# Build settings
markdown: redcarpet
highlighter: pygments
baseurl:/rhythmcity.github.io/
# the subpath of your site, e.g. /blog/
