# Site settings
title: Mr.Tomato的技术博客
header-img: img/home-bg.jpg
email: rhythmcity@163.com
description: “既然选择了一条路，又何必打听要走多久。”
baseurl: ""
url: "http://yourdomain.com"
github_username:  rhythmcity


# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
