# Site settings
title: Mr.Tomato的技术博客
header-img: img/home-bg.jpg
email: rhythmcity@163.com
description: "上帝是个程序员。"
baseurl: ""
url: "http://weibo.com/2674583891/profile?rightmod=1&wvr=6&mod=personinfo"
github_username:  rhythmcity


# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
